### ISSUE TITLE
Component metadata rules are not invoked for project dependencies if they are present in buildscript classpath

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#18]
When I have a dependency in a project and the same dependency in buildscript classpath component metadata rules are not invoked for that dependency

Run `gw dependencies --info` You won't see `Hello from junit:junit:4.12`

Example project: https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/attributesAndBuildScriptClasspath

**Comment by ljacomet** [comment]
Matching Gradle issue: gradle/gradle#4261

**Comment by melix** [comment]
This should be testable with the [latest nightly](https://services.gradle.org/distributions-snapshots/gradle-5.1-20181023100041+0000-bin.zip).

**Comment by OdysseusLives** [comment]
This is verified and looks good!
