### ISSUE TITLE
Deprecated libraries - Modules deprecated outside of .module file are not resolving correctly

### ISSUE THREAD

**Issue by OdysseusLives** [nebula-plugins/gradle-nebula-integration#20]
The [lifecycle plugin dependency-management-sample](https://github.com/chali/dependency-management-samples/tree/master/samples/lifecycle-plugin) contains a demo on how modules can be selected based on their lifecycle status of _alive_, _deprecated_, or _blacklisted_.

In the demo, these attributes are added in the dependency's `.module` file. 

Upon publishing, modules are not going to list themselves with a deprecated or blacklisted lifecycle, so I want to see what this looks like when these attributes are updated later (as through from an external service). There are some unexpected results in `plugin-deprecation-insight-[alive/deprecated].sample.out` in the fork [dependency-management-samples with an update](https://github.com/gradle/dependency-management-samples/compare/master...OdysseusLives:master) where the highest version available is requested, and then the build fails.

What else needs to be done to resolve the dependency when the attributes are updated outside of the module metadata?

**Comment by bigdaz** [comment]
Since the `lifecycle` attribute will be used for "component selection" (choosing the right component version given a version range), then the attribute needs to be set for the entire component, not for each individual variant. So instead of:
```
components.all {
    allVariants {
        attributes {
            attribute(LIFECYCLE_ATTRIBUTE, lifecycle(ALIVE))
        }
    }
}
```

try
```
components.all {
    attributes {
        attribute(LIFECYCLE_ATTRIBUTE, lifecycle(ALIVE))
    }
}
```

An attribute set for a component is automatically set for each variant of the component.

**Comment by OdysseusLives** [comment]
Thank you!
