### ISSUE TITLE
Older Gradle distribution caches are not cleaned up

### ISSUE THREAD

**Issue by OdysseusLives** [nebula-plugins/gradle-nebula-integration#33]
While looking at cache cleanup, I see that shared dependency caches such as directories in `~/.gradle/caches/modules-2` and files in `~/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin` that have not been used recently are cleaned up, but I still see older caches and distributions of Gradle that I have not used in a few months. 

I am verifying the age of these version-specific caches and distributions by using `tree -D -L <depth> <folder-name>` as run in the [script in this repo](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/clear-caches/view-cache-contents.sh). 

For example, in `~/.gradle.caches`, I see the following caches not cleaned up:
```
├── [Apr 11 13:01]  2.13
├── [Apr 24  9:45]  4.5.1
├── [May 22 10:58]  4.6
├── [May 24 12:58]  2.10
├── [Jun 12 18:39]  4.8
├── [Jun 26 12:34]  3.3
├── [Jun 26 14:09]  4.8.1
```
and in `~/.gradle/wrapper/dists`, I see the following distributions:
```
├── [Feb 22  2018]  gradle-4.5.1-bin
├── [Feb 27 12:31]  gradle-2.13-bin
├── [Mar  2  8:54]  gradle-4.6-bin
├── [Jun 13 12:46]  gradle-4.8-bin
├── [Jun 26 12:34]  gradle-3.3-all
├── [Jun 26 12:36]  gradle-4.8.1-bin
├── [Jul 20 10:27]  gradle-2.10-bin
```
in addition to versions that I have used more recently. 

Am I evaluating the age/ "last use" of these version caches the correct way, and these should have been cleaned up?

**Comment by marcphilipp** [comment]
For each version-specific cache in `~/.gradle/caches`, the modification timestamp of `fileHashes/fileHashes.lock` is checked. This file exists in Gradle >= 3.4 so it doesn’t work with earlier versions (2.13 and 3.3 in your case).

For those, the distributions will be deleted if you manually delete `~/.gradle/caches/2.13` and `~/.gradle/caches/3.3` before. In order for the cleanup to run (again), you need to remove `~/.gradle/caches/4.10/gc.properties` (assuming you're running 4.10) or change its modification timestamp to be older than 24 hours.
