### ISSUE TITLE
Dependencies are not aligned when bom is used

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#35]
Dependencies which are marked to belong to the same group and forced to downgrade have are not aligned in this case.

You can see this output `./gradlew dependencies --configuration compile`

```
compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
+--- example:bom:1.0
|    +--- example:platform:2.0
|    |    \--- example:transitive1:1.0
|    |         \--- example:transitive2:1.0
|    |              \--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.2.0 -> 2.9.6
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.9.6 -> 2.8.6
|    \--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.9.6
+--- example:dependency1:1.0
|    \--- example:platform:1.0 -> 2.0 (*)
\--- example:dependency2:1.0
     +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.9.6 -> 2.8.6
     \--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.9.6
```

I would expect all dependencies at the 2.8.6 version. Full example project https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/broken-alignment-with-bom.

Interesting facts are:
* When `bom` is causing the upgrade of `platform` from `1.0` to `2.0` then I see the problem. Direct dependency on `platform:2.0` instead `example:dependency1:1.0` doesn't have this problem.
* It seems that even depth of transitive dependencies in `platform` is playing a role. When `platform` directly depended on `jackson-datatype-guava:2.2.0` I was getting the right version.

**Comment by ljacomet** [comment]
By using Gradle version `5.0-20180910235855+0000` and updating the BOM dependency declaration with `compile platform("example:bom:1.0")`, I cannot reproduce the issue.

Output:
```
compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
+--- example:bom:1.0
|    +--- example:platform:2.0
|    |    \--- example:transitive1:1.0
|    |         \--- example:transitive2:1.0
|    |              \--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.2.0 -> 2.8.6
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.9.6 -> 2.8.6
|    \--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.9.6 -> 2.8.6
+--- example:dependency1:1.0
|    \--- example:platform:1.0 -> 2.0 (*)
\--- example:dependency2:1.0
     +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.9.6 -> 2.8.6
     \--- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.9.6 -> 2.8.6

(*) - dependencies omitted (listed previously)
```

**Comment by ljacomet** [comment]
Any update on this one? The PR I submitted was approved and merged. Does it not show that the problem no longer appears?

**Comment by chali** [comment]
I don't see this type of problem in our results anymore. I'm closing it.
