### ISSUE TITLE
Fail to touch `gc.properties`

### ISSUE THREAD

**Issue by chali** [nebula-plugins/gradle-nebula-integration#36]

**Comment by marcphilipp** [comment]
Is this an issue with cache cleanup?

**Comment by marcphilipp** [comment]
No worries! Yes, `gc.properties` is a marker file that we check for existence/last modification in order to know when to run the cleanup. But there is one per cache so more details would be helpful. 🙂

**Comment by chali** [comment]
I'm thinking due to the nature of our use case. Is it possible to disable this cache cleanup through some property? It is possible that in the docker image we have just one distribution which runs just one single build and then it is thrown away. If yes, that could be a nice workaround.

**Comment by hinshun** [comment]
Unfortunately, using a different JDK to mitigate this issue isn't a viable option for us, so I haven't looked into it. We can work around this through adding precommands to touch or chown the directories but we'll be tying ourselves closer to implementation details as gradle releases new versions.

I'm hoping gradle could either take a stance to either implement `gc.properties` modification time differently or explicitly not supporting this usecase.

**Comment by marcphilipp** [comment]
> Unfortunately, using a different JDK to mitigate this issue isn't a viable option for us, so I haven't looked into it.

I'm not sure it would fix this issue but I'm curious why that isn't an option.

> We can work around this through adding precommands to touch or chown the directories but we'll be tying ourselves closer to implementation details as gradle releases new versions.

I fully agree that this cannot be considered a long-term solution.

> I'm hoping gradle could either take a stance to either implement `gc.properties` modification time differently or explicitly not supporting this usecase.

I guess we could attempt to delete the file and create it again if touching fails. That should work in your setup, right?

**Comment by hinshun** [comment]
> I'm not sure it would fix this issue but I'm curious why that isn't an option.

JDK version is managed by a centralized team, there are support cycles and large amounts of testing before services are migrated to the new base.

> I guess we could attempt to delete the file and create it again if touching fails. That should work in your setup, right?

Yes that would work, thank you.

**Comment by marcphilipp** [comment]
> JDK version is managed by a centralized team, there are support cycles and large amounts of testing before services are migrated to the new base.

Just to be clear, I wasn't suggesting that you migrate any services that you build with Gradle, only to run Gradle on a more recent JVM. You could even use a different JDK for running Gradle than for compiling code etc.

**Comment by hinshun** [comment]
Okay, if we could use a different JDK for running Gradle than for compiling, then it's a possible solution. I'll look into later JDKs if they have moved away from `utime`.

**Comment by hinshun** [comment]
Later JDKs use `utime`, so a more recent JVM isn't an option.

JDK9:
http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/65464a307408/src/java.base/share/classes/java/io/File.java#l1438
http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/ed7c4f86489f/src/java.base/unix/native/libjava/UnixFileSystem_md.c#l403

JDK10:
http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/777356696811/src/java.base/share/classes/java/io/File.java#l1438
http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/777356696811/src/java.base/unix/native/libjava/UnixFileSystem_md.c#l412

JDK11:
http://hg.openjdk.java.net/jdk/jdk11/file/68fa3d4026ea/src/java.base/share/classes/java/io/File.java#l1438
http://hg.openjdk.java.net/jdk/jdk11/file/68fa3d4026ea/src/java.base/unix/native/libjava/UnixFileSystem_md.c#l414

**Comment by marcphilipp** [comment]
Thanks for checking!

**Comment by marcphilipp** [comment]
There may be another solution: `Files.setLastModifiedTime()` seems to use `futimes`, if available:

http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/5c9c7f98d026/src/java.base/unix/classes/sun/nio/fs/UnixFileAttributeViews.java#l114
http://hg.openjdk.java.net/jdk/jdk11/file/68fa3d4026ea/src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c#l654

**Comment by hinshun** [comment]
Interesting. I think that is for `setTimes` so it may still require a change in gradle: https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/BasicFileAttributeView.html#setTimes-java.nio.file.attribute.FileTime-java.nio.file.attribute.FileTime-java.nio.file.attribute.FileTime-

**Comment by marcphilipp** [comment]
Could you please try if it now works in your setup with Gradle 5.0-milestone-1?

**Comment by hinshun** [comment]
Hi @marcphilipp, I haven't been able to test it yet due to on-call duties. I'll try to squeeze some time to test it on Monday.

**Comment by hinshun** [comment]
Sorry for the delay, it seems that `Gradle 5.0-milestone-1` still has the same issues:
```
> Configure project :
[metrics] Build is running offline. Metrics will not be collected.
+===============================================================================
| Nebula 6.0.0-rc.3 on Gradle 5.0-milestone-1
+===============================================================================
BUILD SUCCESSFUL in 7s
1 actionable task: 1 up-to-date
FAILURE: Build failed with an exception.
* What went wrong:
Could not update time stamp for /gradle-project-cache/5.0-milestone-1/gc.properties
> /gradle-project-cache/5.0-milestone-1/gc.properties: Operation not permitted
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.UncheckedIOException: Could not update time stamp for /gradle-project-cache/5.0-milestone-1/gc.properties
```

I think the issue is that `futimes` still requires ownership like `utimes`. See:
- http://man7.org/linux/man-pages/man3/futimes.3.html
- https://github.com/gulpjs/vinyl-fs/issues/127

I think what you want is `futimens`. See:
- http://man7.org/linux/man-pages/man3/futimens.3.html

**Comment by marcphilipp** [comment]
Who knew there were so many ways to set a simple timestamp... 😬

The only workaround I can think of is deleting the file and recreating it.

@hinshun How critical is this issue for you? Could you provide a sample Docker container?

**Comment by chali** [comment]
@hinshun prepared this nice example showing the problem https://github.com/hinshun/java-touch#java-touch

**Comment by marcphilipp** [comment]
@hinshun Thanks for the reproducer!

@chali I'm afraid there's no Java API that calls `futimens`. However, I can implement a different fallback strategy, e.g. execute `touch` or delete the file and create it again. However, since this is the only report of such an issue, I first would like to understand how critical this is for you and if a workaround wouldn't be easier to implement on your end. Moreover, why does this only happen for the project cache dir and not for the caches in the Gradle user home? Are these owned by the user executing the build?

**Comment by hinshun** [comment]
I'd like to point out that there is a different strategy proposed here: https://github.com/hinshun/java-touch/blob/master/Touch.java#L28-L32

**Comment by marcphilipp** [comment]
Thanks, that's indeed a creative solution. 🙂

**Comment by marcphilipp** [comment]
FYI I've created https://github.com/gradle/gradle/issues/7873 to address this for Gradle 5.1.

**Comment by chali** [comment]
Verified with our use case and it is working. Thank you @marcphilipp
