### ISSUE TITLE
`platform` with dynamic version

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-nebula-integration#37]
Used here: https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/blob/de43dfd4154a2349a8cbe1d5df8f88c4d9d30f4f/src/main/groovy/netflix/nebula/dependency/recommender/provider/RecommendationProviderContainer.java#L112-L113

When a platform is added with a dynamic version `org.example:my-bom:latest.candidate`, other dependencies seem to not be getting their versions supplied by this bom.

**Comment by melix** [comment]
Hi @sghill ,

I tried to reproduce this bug but failed. Basically [here's what I did](https://gist.github.com/melix/12da1102eabeedeab70241fe926ed0f2). There's a dependency on a platform using a dynamic version. The platform is going to cause an upgrade of the direct dependencies. I checked with both versions using `1.0` for the direct dependencies and providing no version whatsoever, in both cases, the platform is applied.

That said I'm not surprised: given it's a published platform, there's no difference between this and another dependency: dependencies are treated exactly the same way.

Can you come up with a project that reproduces the problem?

**Comment by bigdaz** [comment]
I also failed to replicate this, using logic more similar to [that used by the nebula-recommender-plugin](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/blob/02f6a5545669bdad352ac20cdb46f4733163acec/src/main/groovy/netflix/nebula/dependency/recommender/ExtendRecommenderConfigurationAction.java).

```
configurations {
   bom
}
dependencies {
    bom platform('org.springframework.boot:spring-boot-dependencies:latest.release')
}

project(':sub') { subproject ->
    configurations {
        conf
    }
    dependencies {
        conf 'com.h2database:h2'
    }
    repositories {
        mavenCentral()
    }

    afterEvaluate {
        def bomCopy = rootProject.configurations['bom'].copy()
        configurations.add(bomCopy)
        configurations.conf.extendsFrom(bomCopy)
    }
}
```

**Comment by sghill** [comment]
This ended up being an issue with mismatched plugin versions.
