### ISSUE TITLE
Removed Configuration has lockfile left behind on regeneration

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-nebula-integration#46]
Given a buildfile such as:
```
apply plugin: 'java'
apply plugin: 'checkstyle'

dependencyLocking { 
    lockAllConfigurations()
}

repositories { jcenter() }

dependencies {
    testImplementation 'junit:junit:4.12'
}
```
When `./gradlew --write-locks dependencies` is executed, a lockfile is generated as expected for each configure.
However when the checkstyle plugin is removed (and its checkstyle configuration disppears) and `./gradlew --write-locks dependencies` is executed, the files are not removed.

**Comment by ljacomet** [comment]
This is tricky to get right due to the dynamic nature of Gradle and the fact that not all configurations can be resolved during a build, or even created.
Because of this, there is currently no plans for adding an _automated delete_ support.
