### ISSUE TITLE
Gradle 5.0-rc-1 dependencies added to compileOnly, testCompileOnly, and annotationProcessor are missed by IntelliJ

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-nebula-integration#55]
JetBrains ticket: [IDEA-201974](https://youtrack.jetbrains.com/issue/IDEA-201974)
Also mentioned on https://github.com/franzbecker/gradle-lombok/issues/56.

This was discovered while upgrading a project that relies on gradle-lombok plugin from Gradle 4.10.2 -> 5.0-rc-1.

**Comment by chali** [comment]
We are tracking this internally and we don't expect any actions from the Gradle team. I'm closing this issue.
