### ISSUE TITLE
POM/Ivy/GM files with null/empty versions

### ISSUE THREAD

**Issue by rpalcolea** [nebula-plugins/gradle-nebula-integration#62]
Given the following repository https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/empty-versions-in-publication-issue

`platform` declares a version for google-collections while `consumer` uses the platform but contains a substitution rule

When running `./gradlew :consumer:dependencies`, we can see the substitution happeing:

We can see the replacement happening

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- com.google.collections:google-collections -> com.google.guava:guava:28.0-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:2.8.1
|    +--- com.google.errorprone:error_prone_annotations:2.3.2
|    +--- com.google.j2objc:j2objc-annotations:1.3
|    \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
\--- com.google.guava:guava:latest.release -> 28.0-jre (*)
```

However, when we generate the POM file, the original dependency (google-collections) still as part of it. And because we use platform, the version is null and that generates an invalid POM/Ivy descriptor which breaks our consumers. Ex.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.gradle.sample</groupId>
  <artifactId>project1-sample</artifactId>
  <version>1.1</version>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>test-substitution</groupId>
        <artifactId>platform</artifactId>
        <version>1.0.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.collections</groupId>
      <artifactId>google-collections</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>28.0-jre</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>

```

`./gradlew :consumer:generatePomFileForMavenPublication` should get you to the above.

This is the same for gradle metadata:

```
"dependencies": [
        {
          "group": "com.google.collections",
          "module": "google-collections",
          "version": {}
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "test-substitution",
          "module": "platform",
          "version": {
            "requires": "1.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        }
      ],
``` 

We applied a workaround at our nebula-publishing-plugin level to prevent POM and Ivy files from having such cases: https://github.com/nebula-plugins/nebula-publishing-plugin/pull/139/files#diff-5aa27442b01d827a59fa155a3aa918ceR20 https://github.com/nebula-plugins/nebula-publishing-plugin/pull/138/files#diff-afec29e02384e8d1bdecac19f9ca8d89R37

As discussed before, gradle metadata doesn’t have a public api to manipulate the resulting module JSON file.

Wondering if this is a bug in gradle or this is the expected behavior? We’d expect gradle to not publish dependencies that were substituted in best case scenario, but I can hear the point of this being an opinion per project level and it might be worth publish this as a substitution as part of module metadata so other projects can apply it? or what’s the thinking behind this?

With that said, I believe it would be nice if Gradle doesn’t write POM/Ivy/Gradle Metadata files with dependencies without versions

**Comment by melix** [comment]
So this is a bug. Now, I'm wondering what is the correct behavior here. It's strange to have a substitution rule for a first level dependency. I can understand this would happen, typically, if you have a plugin which applies rules and that you are not aware of them.

However, what should we do in this case?

Solution 1: substitute in the POM file, make this use case pass. This would be the less intrusive version for you, I guess.

Solution 2: fail the build when we generate metadata, warn that there's a substitution of a first level dependency, which can't be published. We can show what dependency is in play, so that the user fixes the build file.

Solution 3: fail the build independently of publication, but when? Because we would have to resolve something to actually realize a first level dependency was substituted.

Any other idea?

**Comment by melix** [comment]
The PR above implements soution 1.

**Comment by melix** [comment]
If solution 1 above works for you the PR is ready for merge in 5.6.

**Comment by rpalcolea** [comment]
Hi @melix 

Thanks for the quick response.

I believe one is the safest approach since breaking the builds isn’t ideal when users don’t understand what’s really going on there.

I was thinking if one could have a warning that the module was removed but that could make the output a little noisy. What are your thoughts on that?

Other than that, 1 looks great! Thanks for the fix!

**Comment by melix** [comment]
We have long overdue plans on linting and I believe that warning about those should be part of linting.

**Comment by rpalcolea** [comment]
Awesome! Thanks again!

**Comment by melix** [comment]
PR merged, thanks for the report!
